[package]
name = "nekoton_bridge"
version = "0.0.0"
edition = "2018"

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "1.61.*"

[dependencies]
flutter_rust_bridge = "1.61.*"
lazy_static = "1.4.0"
parking_lot = "0.12.1"
simplelog = "0.12.0"
log = { version = "0.4.17", features = ["kv_unstable"] }
oslog = "0.2.0"
